In [11]:
import pandas as pd
import numpy as np
import importlib, dc_sampling_v3 as dc
importlib.reload(dc)

In [13]:
df_1h = pd.read_parquet("/home/jupyter/jim_folder/df_1h.parquet")
# df_1h.head()

# df = pd.read_parquet("/home/jupyter/jim_folder/df_min.parquet")
# df = pd.read_parquet("/home/jupyter/jim_folder/df_min_from_2025-07-16.parquet")
df.head()

,open,high,low,close,tick_volume,volume,spread
timestamp,,,,,,,
2019-07-09 14:00:00+00:00,12561.65,12564.65,12560.65,12560.65,9,0,0
2019-07-09 14:01:00+00:00,12560.65,12560.65,12539.68,12552.66,43,0,0
2019-07-09 14:02:00+00:00,12552.66,12556.66,12545.67,12548.67,26,0,0
2019-07-09 14:03:00+00:00,12548.67,12548.67,12540.67,12544.67,9,0,0
2019-07-09 14:04:00+00:00,12544.67,12544.67,12544.67,12544.67,1,0,0

In [14]:
# Calculate DC events based on df_1h, with threshold of theta
events = dc.dc_events_from_series(df_1h["close"], theta=0.0025, tick_volume=df["tick_volume"], exec_lag_minutes=2)

# Calculate DC events based on df_min, with threshold of theta
# events = dc.dc_events_from_series(df["close"], theta=0.0025, tick_volume=df["tick_volume"], exec_lag_minutes=2)
# events = dc.dc_events_from_series(df["close"], theta=0.0025, tick_volume=df["tick_volume"], exec_lag_minutes=2)

In [15]:
print(events["event"].value_counts())
print("from", events.index.min(), "to", events.index.max())
display(events.tail(5))

event
down_dcc    8180
up_dcc      8179
Name: count, dtype: int64
from 2019-07-09 18:00:00+00:00 to 2025-09-15 05:00:00+00:00

,event,theta,ret_5m,ret_10m,ret_15m,ret_30m,ret_1h,ret_1d,ret_30d,ret_60d,...,t_extreme,dcc_move_log,dcc_move_ret,dcc_move_abs_ret,os_after_log,os_after_ret,os_after_abs_ret,n_obs_between_priorextreme_confirm,n_obs_between_confirm_extreme,dcc_dir
t,,,,,,,,,,,,,,,,,,,,,
2025-09-14 16:00:00+00:00,down_dcc,0.0025,-0.006397,-0.006397,-0.006397,-0.006397,-0.006397,-0.005690,-0.018079,-0.027564,...,2025-09-14 17:00:00+00:00,-0.006840,-0.006816,0.006816,-0.001729,-0.001727,0.001727,2.0,1.0,-1
2025-09-14 19:00:00+00:00,up_dcc,0.0025,0.001149,0.001149,0.001149,0.001149,0.001149,-0.004324,-0.018683,-0.024416,...,2025-09-14 22:00:00+00:00,0.002524,0.002527,0.002527,0.009900,0.009949,0.009949,2.0,3.0,1
2025-09-14 23:00:00+00:00,down_dcc,0.0025,-0.003399,-0.003399,-0.003399,-0.003399,-0.003399,0.003180,-0.011353,-0.019196,...,2025-09-15 01:00:00+00:00,-0.003404,-0.003399,0.003399,-0.012158,-0.012085,0.012085,1.0,2.0,-1
2025-09-15 04:00:00+00:00,up_dcc,0.0025,0.002602,0.002602,0.002602,0.002602,0.002602,-0.006489,-0.020003,-0.024242,...,2025-09-15 04:00:00+00:00,0.003020,0.003025,0.003025,0.000000,0.000000,0.000000,3.0,0.0,1
2025-09-15 05:00:00+00:00,down_dcc,0.0025,-0.003081,-0.003081,-0.003081,-0.003081,-0.003081,-0.009371,-0.026091,-0.026294,...,NaT,-0.003085,-0.003081,0.003081,NaN,NaN,NaN,1.0,NaN,-1

In [5]:
print(events.columns.tolist())

['event', 'theta', 'ret_5m', 'ret_10m', 'ret_15m', 'ret_30m', 'ret_1h', 'ret_1d', 'ret_30d', 'ret_60d', 'vol_5m', 'vol_10m', 'vol_15m', 'vol_30m', 'vol_1h', 'vol_1d', 'vol_30d', 'vol_60d', 'ema_dist_std_5m', 'ema_dist_std_10m', 'ema_dist_std_15m', 'ema_dist_std_30m', 'ema_dist_std_1h', 'ema_dist_std_1d', 'ema_dist_std_30d', 'ema_dist_std_60d', 'vol_ratio_5m_30m', 'vol_ratio_15m_1h', 'vol_ratio_30m_1d', 'rsi_5m', 'rsi_10m', 'rsi_15m', 'rsi_30m', 'rsi_1h', 'rsi_1d', 'macd_5m', 'macd_signal_5m', 'macd_hist_5m', 'macd_10m', 'macd_signal_10m', 'macd_hist_10m', 'macd_15m', 'macd_signal_15m', 'macd_hist_15m', 'macd_30m', 'macd_signal_30m', 'macd_hist_30m', 'macd_1h', 'macd_signal_1h', 'macd_hist_1h', 'macd_1d', 'macd_signal_1d', 'macd_hist_1d', 'tickvol_avg_5m', 'tickvol_avg_10m', 'tickvol_avg_15m', 'tickvol_avg_30m', 'tickvol_avg_1h', 'tickvol_avg_1d', 'tickvol_avg_30d', 'tickvol_avg_60d', 'p_prior_extreme', 't_prior_extreme', 'p_t', 't_confirm', 't_execute', 'p_t_execute', 'tradable_flag', 'p_extreme', 't_extreme', 'dcc_move_log', 'dcc_move_ret', 'dcc_move_abs_ret', 'os_after_log', 'os_after_ret', 'os_after_abs_ret', 'n_obs_between_priorextreme_confirm', 'n_obs_between_confirm_extreme', 'dcc_dir']

In [6]:
cols = [
    "p_prior_extreme","t_prior_extreme",
    "p_t","t_confirm",
    "p_t_execute","t_execute",
    'p_extreme', 't_extreme',
    "tradable_flag", "dcc_dir", 
]
display(events[cols].head(20))
display(events[cols].tail(20))

,p_prior_extreme,t_prior_extreme,p_t,t_confirm,p_t_execute,t_execute,p_extreme,t_extreme,tradable_flag,dcc_dir
t,,,,,,,,,,
2019-07-09 14:25:00+00:00,12604.60,2019-07-09 14:22:00+00:00,12571.64,2019-07-09 14:25:00+00:00,12574.64,2019-07-09 14:27:00+00:00,12521.70,2019-07-09 14:49:00+00:00,True,-1
2019-07-09 14:56:00+00:00,12521.70,2019-07-09 14:49:00+00:00,12553.66,2019-07-09 14:56:00+00:00,12574.64,2019-07-09 14:58:00+00:00,12582.63,2019-07-09 14:57:00+00:00,True,1
2019-07-09 14:59:00+00:00,12582.63,2019-07-09 14:57:00+00:00,12548.67,2019-07-09 14:59:00+00:00,12525.69,2019-07-09 15:01:00+00:00,12525.69,2019-07-09 15:01:00+00:00,True,-1
2019-07-09 15:07:00+00:00,12525.69,2019-07-09 15:01:00+00:00,12589.62,2019-07-09 15:07:00+00:00,12575.64,2019-07-09 15:09:00+00:00,12864.32,2019-07-09 15:31:00+00:00,True,1
2019-07-09 15:35:00+00:00,12864.32,2019-07-09 15:31:00+00:00,12830.36,2019-07-09 15:35:00+00:00,12838.35,2019-07-09 15:37:00+00:00,12818.37,2019-07-09 15:43:00+00:00,True,-1
2019-07-09 15:52:00+00:00,12818.37,2019-07-09 15:43:00+00:00,12854.33,2019-07-09 15:52:00+00:00,12880.30,2019-07-09 15:54:00+00:00,12880.30,2019-07-09 15:54:00+00:00,True,1
2019-07-09 15:55:00+00:00,12880.30,2019-07-09 15:54:00+00:00,12830.36,2019-07-09 15:55:00+00:00,12851.33,2019-07-09 15:57:00+00:00,12830.36,2019-07-09 15:55:00+00:00,True,-1
2019-07-09 15:59:00+00:00,12830.36,2019-07-09 15:55:00+00:00,12868.31,2019-07-09 15:59:00+00:00,12878.30,2019-07-09 16:01:00+00:00,12897.28,2019-07-09 16:07:00+00:00,True,1
2019-07-09 16:08:00+00:00,12897.28,2019-07-09 16:07:00+00:00,12863.32,2019-07-09 16:08:00+00:00,12863.32,2019-07-09 16:10:00+00:00,12850.33,2019-07-09 16:13:00+00:00,True,-1
2019-07-09 16:19:00+00:00,12850.33,2019-07-09 16:13:00+00:00,12894.29,2019-07-09 16:19:00+00:00,12885.30,2019-07-09 16:21:00+00:00,12963.21,2019-07-09 16:29:00+00:00,True,1
2019-07-09 16:31:00+00:00,12963.21,2019-07-09 16:29:00+00:00,12927.25,2019-07-09 16:31:00+00:00,12906.27,2019-07-09 16:33:00+00:00,12868.31,2019-07-09 16:32:00+00:00,False,-1
2019-07-09 16:33:00+00:00,12868.31,2019-07-09 16:32:00+00:00,12906.27,2019-07-09 16:33:00+00:00,12907.27,2019-07-09 16:35:00+00:00,13067.09,2019-07-09 17:10:00+00:00,True,1
2019-07-09 17:11:00+00:00,13067.09,2019-07-09 17:10:00+00:00,13029.14,2019-07-09 17:11:00+00:00,13023.14,2019-07-09 17:13:00+00:00,13018.15,2019-07-09 17:12:00+00:00,True,-1
2019-07-09 17:16:00+00:00,13018.15,2019-07-09 17:12:00+00:00,13056.11,2019-07-09 17:16:00+00:00,13064.10,2019-07-09 17:18:00+00:00,13089.07,2019-07-09 17:20:00+00:00,True,1
2019-07-09 17:22:00+00:00,13089.07,2019-07-09 17:20:00+00:00,13041.12,2019-07-09 17:22:00+00:00,13053.11,2019-07-09 17:24:00+00:00,13025.14,2019-07-09 17:27:00+00:00,True,-1
2019-07-09 17:30:00+00:00,13025.14,2019-07-09 17:27:00+00:00,13060.10,2019-07-09 17:30:00+00:00,13040.12,2019-07-09 17:32:00+00:00,13060.10,2019-07-09 17:30:00+00:00,True,1
2019-07-09 17:33:00+00:00,13060.10,2019-07-09 17:30:00+00:00,13014.15,2019-07-09 17:33:00+00:00,12964.21,2019-07-09 17:35:00+00:00,12932.24,2019-07-09 17:36:00+00:00,True,-1
2019-07-09 17:37:00+00:00,12932.24,2019-07-09 17:36:00+00:00,12973.20,2019-07-09 17:37:00+00:00,12984.19,2019-07-09 17:39:00+00:00,13100.06,2019-07-09 18:06:00+00:00,True,1
2019-07-09 18:13:00+00:00,13100.06,2019-07-09 18:06:00+00:00,13034.13,2019-07-09 18:13:00+00:00,13025.14,2019-07-09 18:15:00+00:00,12971.20,2019-07-09 18:22:00+00:00,True,-1
2019-07-09 18:24:00+00:00,12971.20,2019-07-09 18:22:00+00:00,13011.16,2019-07-09 18:24:00+00:00,12980.19,2019-07-09 18:26:00+00:00,13011.16,2019-07-09 18:24:00+00:00,True,1

,p_prior_extreme,t_prior_extreme,p_t,t_confirm,p_t_execute,t_execute,p_extreme,t_extreme,tradable_flag,dcc_dir
t,,,,,,,,,,
2025-09-14 12:04:00+00:00,115691.46,2025-09-14 10:40:00+00:00,115402.55,2025-09-14 12:04:00+00:00,115363.44,2025-09-14 12:06:00+00:00,115361.80,2025-09-14 12:05:00+00:00,True,-1
2025-09-14 12:34:00+00:00,115361.80,2025-09-14 12:05:00+00:00,115662.45,2025-09-14 12:34:00+00:00,115665.57,2025-09-14 12:36:00+00:00,116122.05,2025-09-14 14:47:00+00:00,True,1
2025-09-14 16:08:00+00:00,116122.05,2025-09-14 14:47:00+00:00,115806.24,2025-09-14 16:08:00+00:00,115734.50,2025-09-14 16:10:00+00:00,114873.11,2025-09-14 18:14:00+00:00,True,-1
2025-09-14 18:29:00+00:00,114873.11,2025-09-14 18:14:00+00:00,115197.49,2025-09-14 18:29:00+00:00,115287.26,2025-09-14 18:31:00+00:00,116762.82,2025-09-14 23:09:00+00:00,True,1
2025-09-14 23:26:00+00:00,116762.82,2025-09-14 23:09:00+00:00,116469.02,2025-09-14 23:26:00+00:00,116455.08,2025-09-14 23:28:00+00:00,115484.67,2025-09-15 01:15:00+00:00,True,-1
2025-09-15 01:24:00+00:00,115484.67,2025-09-15 01:15:00+00:00,115789.12,2025-09-15 01:24:00+00:00,115814.89,2025-09-15 01:26:00+00:00,115816.02,2025-09-15 01:25:00+00:00,True,1
2025-09-15 01:35:00+00:00,115816.02,2025-09-15 01:25:00+00:00,115494.83,2025-09-15 01:35:00+00:00,115456.64,2025-09-15 01:37:00+00:00,114737.28,2025-09-15 02:00:00+00:00,True,-1
2025-09-15 02:22:00+00:00,114737.28,2025-09-15 02:00:00+00:00,115120.39,2025-09-15 02:22:00+00:00,115093.50,2025-09-15 02:24:00+00:00,115150.23,2025-09-15 02:26:00+00:00,True,1
2025-09-15 03:12:00+00:00,115150.23,2025-09-15 02:26:00+00:00,114846.82,2025-09-15 03:12:00+00:00,114860.86,2025-09-15 03:14:00+00:00,114766.43,2025-09-15 04:08:00+00:00,True,-1
2025-09-15 04:14:00+00:00,114766.43,2025-09-15 04:08:00+00:00,115080.56,2025-09-15 04:14:00+00:00,115048.89,2025-09-15 04:16:00+00:00,115206.96,2025-09-15 04:38:00+00:00,True,1
2025-09-15 05:08:00+00:00,115206.96,2025-09-15 04:38:00+00:00,114907.26,2025-09-15 05:08:00+00:00,114957.80,2025-09-15 05:10:00+00:00,114664.03,2025-09-15 06:01:00+00:00,True,-1
2025-09-15 06:27:00+00:00,114664.03,2025-09-15 06:01:00+00:00,114983.78,2025-09-15 06:27:00+00:00,115043.04,2025-09-15 06:29:00+00:00,115092.08,2025-09-15 06:32:00+00:00,True,1
2025-09-15 06:37:00+00:00,115092.08,2025-09-15 06:32:00+00:00,114800.00,2025-09-15 06:37:00+00:00,114722.65,2025-09-15 06:39:00+00:00,114465.17,2025-09-15 06:43:00+00:00,True,-1
2025-09-15 06:47:00+00:00,114465.17,2025-09-15 06:43:00+00:00,114769.04,2025-09-15 06:47:00+00:00,114579.55,2025-09-15 06:49:00+00:00,114874.21,2025-09-15 06:52:00+00:00,True,1
2025-09-15 07:01:00+00:00,114874.21,2025-09-15 06:52:00+00:00,114564.29,2025-09-15 07:01:00+00:00,114580.81,2025-09-15 07:03:00+00:00,114493.94,2025-09-15 07:09:00+00:00,True,-1
2025-09-15 07:20:00+00:00,114493.94,2025-09-15 07:09:00+00:00,114819.05,2025-09-15 07:20:00+00:00,114847.22,2025-09-15 07:22:00+00:00,115042.04,2025-09-15 07:29:00+00:00,True,1
2025-09-15 07:57:00+00:00,115042.04,2025-09-15 07:29:00+00:00,114732.03,2025-09-15 07:57:00+00:00,114699.13,2025-09-15 07:59:00+00:00,114468.69,2025-09-15 08:17:00+00:00,True,-1
2025-09-15 08:39:00+00:00,114468.69,2025-09-15 08:17:00+00:00,114811.11,2025-09-15 08:39:00+00:00,114819.18,2025-09-15 08:41:00+00:00,114924.02,2025-09-15 09:15:00+00:00,True,1
2025-09-15 09:30:00+00:00,114924.02,2025-09-15 09:15:00+00:00,114633.76,2025-09-15 09:30:00+00:00,114788.42,2025-09-15 09:32:00+00:00,114633.76,2025-09-15 09:30:00+00:00,True,-1
2025-09-15 09:43:00+00:00,114633.76,2025-09-15 09:30:00+00:00,114929.83,2025-09-15 09:43:00+00:00,114881.20,2025-09-15 09:45:00+00:00,NaN,NaT,False,1

In [12]:
events["os_ratio"] = events["os_after_ret"].div(events["dcc_move_ret"])
events["os_ratio"] = events["os_ratio"].replace([np.inf, -np.inf], np.nan)

events[["dcc_move_ret","os_after_ret","os_ratio","ret_1h","ret_1d","ret_30d","ret_60d"]].describe(percentiles=[0.01,0.05,0.10,0.25,0.5,0.75,0.9,0.95,0.99])

,dcc_move_ret,os_after_ret,os_ratio,ret_1h,ret_1d,ret_30d,ret_60d
count,136062.000000,136061.000000,136061.000000,136059.000000,135903.000000,132989.000000,131138.000000
mean,0.000017,0.000021,1.050179,-0.000677,-0.003019,0.052947,0.138382
std,0.003486,0.005575,1.391643,0.012737,0.050028,0.259260,0.414501
min,-0.050389,-0.148488,-0.000000,-0.210996,-0.466900,-0.602571,-0.572945
1%,-0.006238,-0.015629,0.000000,-0.037393,-0.140331,-0.462022,-0.479859
5%,-0.004198,-0.008071,0.000000,-0.018968,-0.083992,-0.316576,-0.386446
10%,-0.003573,-0.005347,0.000000,-0.012287,-0.057692,-0.256978,-0.324289
25%,-0.002909,-0.001898,0.108467,-0.004827,-0.025852,-0.113901,-0.162776
50%,0.000003,0.000000,0.616292,-0.000352,-0.001598,0.017116,0.060364
75%,0.002910,0.001920,1.460191,0.003711,0.021501,0.204004,0.357651
90%,0.003595,0.005401,2.634515,0.010324,0.049950,0.384280,0.696330
95%,0.004246,0.008236,3.584258,0.016452,0.071905,0.496115,0.981795
99%,0.006563,0.016079,6.288348,0.034469,0.133062,0.868748,1.455364
max,0.052681,0.146179,51.580960,0.327312,0.380476,1.306295,1.781695

In [8]:
t0 = events.index[-1000]
p_now = df["close"].loc[t0]

t_anchor = t0 - pd.Timedelta(days=60)
p_anchor = df["close"].loc[:t_anchor].iloc[-1]   # asof anchor

print("p_now", p_now, "p_anchor", p_anchor, "ret60d", p_now/p_anchor - 1)
print("events ret60d:", events.loc[t0, "ret_60d"])

p_now 116529.19 p_anchor 105607.66 ret60d 0.10341607796252661
events ret60d: 0.10341607796252661

In [9]:
# Save DC events df for processing
# events.to_parquet("DC_events_1min_from_2025-07-16.parquet", index=True)
# events.to_parquet("DC_events_1min.parquet", index=True)